<?php

require_once dirname(__FILE__) . '/../bootstrap.php';
require_once dirname(__FILE__) . '/../../../src/Magnify.php';

/**
 * Test class for ActivityResource.
 * Generated by PHPUnit on 2012-03-28 at 14:47:30.
 */
class ActivityResourceTest extends PHPUnit_Framework_TestCase
{

  /**
   * @var Magnify
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Magnify(MAGNIFY_CHANNEL, MAGNIFY_API_KEY);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @covers ActivityResource::content
   */
  public function testContent()
  {
    $this->markTestIncomplete('Not implemented');
    /* @var $activity ActivityResource */
    $activity = $this->object->activity;
    $content = $activity->content('857HR4V69HLGG9DY');

    $this->assertInstanceOf('ActivityFeed', $content);
  }

}
