<?php

require_once dirname(__FILE__) . '/../bootstrap.php';
require_once dirname(__FILE__) . '/../../../src/Magnify.php';
require_once dirname(__FILE__) . '/../../../src/Resource/Activity.php';
require_once dirname(__FILE__) . '/../../../src/Feed/Activity.php';

/**
 * Test class for ActivityResource.
 * Generated by PHPUnit on 2012-03-28 at 14:47:30.
 */
class ActivityResourceTest extends PHPUnit_Framework_TestCase
{

  /**
   * @var ActivityResource
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $magnify = new Magnify(MAGNIFY_CHANNEL, MAGNIFY_API_KEY);

    $this->object = $magnify->activity;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @covers ActivityResource::content
   */
  public function testContent()
  {
    $content = $this->object->content('857HR4V69HLGG9DY');

    $this->assertInstanceOf('ActivityFeed', $content);
  }

}
