<?php

require_once dirname(__FILE__) . '/../bootstrap.php';
require_once dirname(__FILE__) . '/../../../src/Magnify.php';
require_once dirname(__FILE__) . '/../../../src/Resource/Content.php';
require_once dirname(__FILE__) . '/../../../src/Feed/Content.php';

/**
 * Test class for ActivityResource.
 * Generated by PHPUnit on 2012-03-28 at 14:47:30.
 */
class ContentResourceTest extends PHPUnit_Framework_TestCase
{

  /**
   * @var ContentResource
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $magnify = new Magnify(MAGNIFY_CHANNEL, MAGNIFY_API_KEY);

    $this->object = $magnify->content;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @covers ContentResource::show
   */
  public function testShow()
  {
    $content = $this->object->show('TKPJWG3RRZXFGC80');

    $this->assertInstanceOf('ContentEntry', $content);
  }

  /**
   * @covers ContentResource::browse
   */
  public function testBrowse()
  {
    $content = $this->object->browse(); //browse (1,10,'recent')

    $this->assertInstanceOf('ContentFeed', $content);
  }

  /**
   * @covers ContentResource::find
   */
  public function testFind()
  {
    $content = $this->object->find('Taylor'); //find('Taylor', 1, 10, 'recent')

    $this->assertInstanceOf('ContentFeed', $content);
  }

  /**
   * @covers ContentResource::user
   */
  public function testUser()
  {
    $content = $this->object->user('N83GN7T7G4BM4MJJ');

    $this->assertInstanceOf('ContentFeed', $content);
  }

}
