<?php

require_once dirname(__FILE__) . '/../bootstrap.php';
require_once dirname(__FILE__) . '/../../../src/Magnify.php';
require_once dirname(__FILE__) . '/../../../src/Resource/Playlist.php';
require_once dirname(__FILE__) . '/../../../src/Feed/Playlist.php';

/**
 * Test class for PlaylistResource.
 * Generated by PHPUnit on 2012-03-28 at 14:47:30.
 */
class PlaylistResourceTest extends PHPUnit_Framework_TestCase
{

  /**
   * @var PlaylistResource
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $magnify = new Magnify(MAGNIFY_CHANNEL, MAGNIFY_API_KEY);

    $this->object = $magnify->playlist;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @covers PlaylistResource::show
   */
  public function testShow()
  {
    $playlist = $this->object->show('DST5G2X0BM26MRXY');

    $this->assertInstanceOf('PlaylistEntry', $playlist);
  }

  /**
   * @covers PlaylistResource::browse
   */
  public function testBrowse()
  {
    $playlists = $this->object->browse();

    $this->assertInstanceOf('PlaylistFeed', $playlists);
  }

  /**
   * @covers PlaylistResource::user
   */
  public function testUser()
  {
    $playlists = $this->object->user('DST5G2X0BM26MRXY');

    $this->assertInstanceOf('PlaylistFeed', $playlists);
  }

}
