<?php

require_once dirname(__FILE__) . '/../bootstrap.php';
require_once dirname(__FILE__) . '/../../../src/Magnify.php';

/**
 * Test class for PlaylistResource.
 * Generated by PHPUnit on 2012-03-28 at 14:47:30.
 */
class PlaylistResourceTest extends PHPUnit_Framework_TestCase
{

  /**
   * @var Magnify
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Magnify(MAGNIFY_CHANNEL, MAGNIFY_API_KEY);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @covers PlaylistResource::show
   */
  public function testShow()
  {
    $this->markTestIncomplete('This test has not been implemented yet');
  }

  /**
   * @covers PlaylistResource::browse
   */
  public function testBrowse()
  {
    $this->markTestIncomplete('This test has not been implemented yet');
  }

  /**
   * @covers PlaylistResource::user
   */
  public function testUser()
  {
    $this->markTestIncomplete('This test has not been implemented yet');
  }

}
