<?php

require_once dirname(__FILE__) . '/../bootstrap.php';
require_once dirname(__FILE__) . '/../../../src/Magnify.php';
require_once dirname(__FILE__) . '/../../../src/Resource/User.php';
require_once dirname(__FILE__) . '/../../../src/Feed/User.php';
require_once dirname(__FILE__) . '/../../../src/Entry/User.php';

/**
 * Test class for UserResource.
 * Generated by PHPUnit on 2012-03-28 at 14:47:30.
 */
class UserResourceTest extends PHPUnit_Framework_TestCase
{

  /**
   * @var UserResource
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $magnify = new Magnify(MAGNIFY_CHANNEL, MAGNIFY_API_KEY);

    $this->object = $magnify->user;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @covers UserResource::show
   */
  public function testShow()
  {
    $entry = $this->object->show('N83GN7T7G4BM4MJJ');

    $this->assertInstanceOf('UserEntry', $entry);
  }

  /**
   * @covers UserResource::find
   */
  public function testFind()
  {
    $users = $this->object->find('J.R. Dobbs');

    $this->assertInstanceOf('MagnifyFeed', $users);
  }

}
